In [2]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
x.dot([2,2,1])

array([ 9, 24])

In [4]:
x * [[1],[0]]

array([[1, 2, 3],
       [0, 0, 0]])

In [7]:
import scipy.constants
fahrenheit = 212
scipy.constants.convert_temperature(fahrenheit, 'Fahrenheit', 'Celsius')

100.0

In [8]:
scipy.constants.physical_constants['electron mass']

(9.1093837015e-31, 'kg', 2.8e-40)

In [9]:
import decimal
import fractions
from numbers import Complex, Real, Rational, Integral

d = decimal.Decimal(1.11, decimal.Context(prec=5))  # precision

for x in (3, fractions.Fraction(2,3), 2.7, complex(1,2), d):
    print('{:>10}'.format(str(x)[:8]),
          [isinstance(x, y) for y in (Complex, Real, Rational, Integral)])

         3 [True, True, True, True]
       2/3 [True, True, True, False]
       2.7 [True, True, False, False]
    (1+2j) [True, False, False, False]
  1.110000 [False, False, False, False]


In [10]:
import sympy as sym

x = sym.Symbol('x')
f = sym.exp(-x**2/2) / sym.sqrt(2 * sym.pi)
f

sqrt(2)*exp(-x**2/2)/(2*sqrt(pi))

In [11]:
sym.integrate(f, x)

erf(sqrt(2)*x/2)/2

In [12]:
sym.N(sym.integrate(f, (x, -1, 1)))

0.682689492137086

In [13]:
'Grünwalder Straße'.upper()

'GRÜNWALDER STRASSE'

In [14]:
'Grünwalder Straße'.lower()

'grünwalder straße'

In [15]:
'Grünwalder Straße'.casefold()

'grünwalder strasse'

In [16]:
import difflib
capitals = ('Montgomery', 'Juneau', 'Phoenix', 'Little Rock')
difflib.get_close_matches('Fenix', capitals)

['Phoenix']

In [23]:
import nltk
nltk.download('punkt', download_dir='/home/af/Dokumenter/Programs/miniconda3/envs/HitchhikersGuide2Python-py38/nltk_data')

[nltk_data] Downloading package punkt to /home/af/Dokumenter/Programs/
[nltk_data]     miniconda3/envs/HitchhikersGuide2Python-
[nltk_data]     py38/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [24]:
import nltk
from nltk.corpus import stopwords
import string

stopwords.ensure_loaded()
text = open('../data/zen.txt').read()
tokens = [
    t.casefold() for t in nltk.tokenize.word_tokenize(text)
    if t not in string.punctuation
]

counter = {}
for bigram in nltk.bigrams(tokens):
    counter[bigram] = 1 if bigram not in counter else counter[bigram] + 1

def print_counts(counter):  # We'll reuse this
    for ngram, count in sorted(
            counter.items(), key=lambda kv: kv[1], reverse=True):
        if count > 1:
            print('{:>25}: {}'.format(str(ngram), '*' * count))

print_counts(counter)

       ('better', 'than'): ********
         ('is', 'better'): *******
            ('one', '--'): **
            ('if', 'the'): **
('the', 'implementation'): **
 ('implementation', 'is'): **
        ('to', 'explain'): **
        ('explain', 'it'): **


In [25]:
kept_tokens = [t for t in tokens if t not in stopwords.words()]

from collections import Counter
c = Counter(kept_tokens)
c.most_common(5)

[('better', 8), ('although', 3), ('never', 3), ('--', 3), ('idea', 3)]

In [27]:
from PIL import Image, ImageFilter
# Read image
im = Image.open( '../data/image.jpeg' )
# Display image
im.show()

# Applying a filter to the image
im_sharp = im.filter( ImageFilter.SHARPEN )
#Saving the filtered image to a new file
im_sharp.save( '../data/image_sharpened.jpeg', 'JPEG' )

# Splitting the image into its respective bands (i.e., Red, Green,
# and Blue for RGB)
r,g,b = im_sharp.split()

# Viewing EXIF data embedded in image
exif_data = im._getexif()
exif_data

In [ ]:
from cv2 import *
import numpy as np
#Read Image
img = cv2.imread('../data/testimg.jpeg')
#Display Image
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#Applying Grayscale filter to image
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#Saving filtered image to new file
cv2.imwrite('../data/graytest.jpeg',gray)
